<a href="https://colab.research.google.com/github/Innovatewithapple/NeuralNetwork/blob/main/NeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x_1 = 0.1
x_2 = 0.8
w_1 = 0.5
w_2 = 0.4
b_1 = 0.3

In [ ]:
z = x_1*w_1+x_2*w_2+b_1
z

0.67

In [ ]:
#Sigmoid
a_1 = 1/(1.0 + np.exp(-z))
a_1

np.float64(0.6615031592029524)

In [ ]:
# Another
weights = np.around(np.random.uniform(size=6),decimals=2)

bias = np.around(np.random.uniform(size=3),decimals=2)

In [ ]:

bias

array([0.47, 0.34, 0.32])

In [ ]:
weights

array([0.72, 0.06, 0.74, 0.52, 0.66, 0.25])

In [ ]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

In [ ]:
z_11 = x_1 * weights[0] + x_2 * weights[1] + bias[0]
print(z_11)

0.881


In [ ]:
z_12 = x_1 * weights[2] + x_2 * weights[3] + bias[1]
print(z_12)

1.1520000000000001


In [ ]:
# Perform Sigmoid
a_11 = 1 / (1.0 + np.exp(-z_11))
print(a_11)

0.41436833609224244


In [ ]:
a_12 = 1 / (1.0 + np.exp(-z_12))
print(a_12)

0.31600412869186245


In [ ]:
z_21 = a_11 * weights[4] + a_12 * weights[5] + bias[2]
print(z_21)

0.6724841339938457


In [ ]:
a_21 = 1 / (1.0 + np.exp(-z_21))

In [ ]:
print(a_21)

0.662059175005703


Activation function with loss function

In [10]:
# Sigmoid-Activation
# 1/(1-e^-z)
zArr = [-1, 0, 1]
TArr = [0, 1, 1]   # targets

for z, T in zip(zArr, TArr):
    a = 1/(1+np.exp(-z))
    # Sigmoid-
    # Loss = -[T*log(a) + (1-T)*log(1-a)]
    loss = -(T*np.log(a) + (1-T)*np.log(1-a))

    print("z:", z, "a:", round(a,3), "Loss:", round(loss,3))

z: -1 a: 0.269 Loss: 0.313
z: 0 a: 0.5 Loss: 0.693
z: 1 a: 0.731 Loss: 0.313


In [14]:
X = np.array([[0,0],[0,1],[1,0],[1,1]]).T
d = [0,1,1,0]
X

array([[0, 0, 1, 1],
       [0, 1, 0, 1]])

In [16]:
a = np.random.rand(2,3)
a

array([[0.95532256, 0.85846917, 0.03530614],
       [0.37880071, 0.08154855, 0.64910423]])

In [33]:
def initialize_parameters(layers):
    weights = []
    biases = []

    for i in range(len(layers)-1):
        print('i:',i)
        w = np.random.rand(layers[i+1], layers[i]) * 2 - 1
        b = np.random.rand(layers[i+1], 1) * 2 - 1
        print('w:',w)
        weights.append(w)
        biases.append(b)

    return weights, biases

layers = [2, 3, 4, 2, 1]

weights, biases = initialize_parameters(layers)

weights

i: 0
w: [[ 0.60330724 -0.53547746]
 [ 0.05550402  0.35901278]
 [ 0.51786433  0.54010596]]
i: 1
w: [[-0.78070445 -0.6158512  -0.35579959]
 [-0.66226868 -0.71549577  0.22477208]
 [-0.40871981 -0.7898288   0.20515587]
 [ 0.66334164 -0.85700052 -0.76405117]]
i: 2
w: [[-0.46843573  0.7847934  -0.1866991  -0.44864847]
 [ 0.93393107  0.37601328  0.64852575 -0.43928485]]
i: 3
w: [[-0.86102514 -0.55835263]]


[array([[ 0.60330724, -0.53547746],
        [ 0.05550402,  0.35901278],
        [ 0.51786433,  0.54010596]]),
 array([[-0.78070445, -0.6158512 , -0.35579959],
        [-0.66226868, -0.71549577,  0.22477208],
        [-0.40871981, -0.7898288 ,  0.20515587],
        [ 0.66334164, -0.85700052, -0.76405117]]),
 array([[-0.46843573,  0.7847934 , -0.1866991 , -0.44864847],
        [ 0.93393107,  0.37601328,  0.64852575, -0.43928485]]),
 array([[-0.86102514, -0.55835263]])]

In [36]:
w = np.random.rand(3,3) * 2
w

array([[1.58751669, 0.0958364 , 1.77373184],
       [1.29650584, 0.11374182, 0.95395063],
       [1.39954408, 0.02217203, 1.96514068]])